eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service.uri:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    responseCode: 200
    bad_request: 403
    conflict: 409
